@base_url = http://localhost:8080


### Health check
GET {{base_url}}/health


### Add customer
POST {{base_url}}/customers
content-type: application/json

{
    "firstName": "Pop",
    "lastName": "Bang",
    "birthday": "2000-01-01",
    "country": "JoJoLands"
}

### Update customer
PUT {{base_url}}/customers/1
content-type: application/json

{
    "firstName": "Poop",
    "lastName": "Bing",
    "birthday": "2000-01-01",
    "notes": "morbidly obese"
}


### Get customer by id
GET {{base_url}}/customers/1

### Search customer
GET {{base_url}}/customers?query=

### Record a visit
POST {{base_url}}/visits/1

{
    "visitDate": "2000-10-10",
    "notes": "He farted"
}

### Get visit
GET {{base_url}}/visits
    ?begin=2000-07-20
    &end=