name: Build Backend Win64

on:
  workflow_dispatch:

env:
  WORK_DIR: backend
  ARTIFACT_NAME: backend-win64

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      working-directory: ${{ env.WORK_DIR }}
      run: go build -v -ldflags="-s -w" -trimpath -o ${{ env.ARTIFACT_NAME }}.exe .

    - name: Upload # This happens only when manually requested
      if: github.ref_type != 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.WORK_DIR }}/${{ env.ARTIFACT_NAME }}.exe

    # Due to Windows' anti-virus policy, do not release win64 version