name: Build Backend Ubuntu

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  WORK_DIR: backend
  ARTIFACT_NAME: backend-ubuntu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      working-directory: ${{ env.WORK_DIR }}
      run: go build -v -ldflags="-s -w" -trimpath -o ${{ env.ARTIFACT_NAME }} .

    - name: Upload # This happens only when manually requested
      if: github.ref_type != 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.WORK_DIR }}/${{ env.ARTIFACT_NAME }}

    - name: Release # This happens only when tags are pushed
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        name: Release ${{ github.ref_name }}
        files: ${{ env.WORK_DIR }}/${{ env.ARTIFACT_NAME }}